server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order-feign-hystrix80
    prefer-ip-address: true    #访问路径可以显示ip

#支持
feign:
  hystrix:
    enabled: true